Simulab/Models/Simulations/Enums/SimConfigDataLifeType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Simulab.Models.Simulations.Enums
{
    public enum SimnConfigDataLifeType
    {
        Session,
        Longterm
    }
}

Simulab/Models/Simulations/Enums/SimConfigTargetEnvironmentType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Simulab.Models.Simulations.Enums
{
    public enum SimConfigTargetEnvironmentType
    {
        AWS,
        Localhost
    }
}

Simulab/Models/Simulations/Enums/SimConfigTargetLanguageType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Simulab.Models.Simulations.Enums
{
    public enum SimConfigTargetLanguageType
    {
        C,
        Fortran,
        Cuda
    }
}

Simulab/Models/Simulations/Enums/SimConfigTreatmentSettingType.cs
namespace Simulab.Models.Simulations.Enums
{
    public enum SimConfigTreatmentSettingType
    {
        None
    }
}

Simulab/Controllers/SimulationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Simulab.Models.Database_Models;
using System.IO;
using System.Reflection;
using System.Diagnostics;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;

namespace Simulab.Controllers
{
    [Authorize]
    public class SimulationController : Controller
    {
        private SimulabContext _context = new SimulabContext();

        private readonly UserManager<UserModel> _userManager;
        public SimulationController(UserManager<UserModel> userManager)
        {
            _userManager = userManager;
        }
        /// <summary>
        /// Return simulation page
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Simulation()
        {
            return View();
        }

        /// <summary>
        /// Return configurator page
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Configurator()
        {
            return View(new SimulationConfigurationModel { UserId = _userManager.GetUserId(User) });
        }

        /// <summary>
        /// Submit configuration result to simulation dispatcher
        /// </summary>
        /// <param name="m"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Configurator(SimulationConfigurationModel m)
        {
            if (ModelState.IsValid)
            {
                m.Date = DateTime.UtcNow;
                _context.SimConfTable.Add(m);
                await _context.SaveChangesAsync();
                return RedirectToAction("Result", new { id = m.Id });
            }
            else
            {
                return View(m);
            }
        }

        /// <summary>
        /// Return Model select component
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> ConfiguratorModelSelect()
        {
            return PartialView(await new ModelController(null).GetModelList(_userManager.GetUserId(User)));
        }

        /// <summary>
        /// return Initial Condition table
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> ConfiguratorICs(int id)
        {
            ModelItemModel m = await _context.ModelTable.FirstOrDefaultAsync(x => x.Id == id);
            return PartialView(m);
        }

        /// <summary>
        /// Return history page
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> History()
        {
            List<SimulationConfigurationModel> configs = _context.SimConfTable.Where(x => x.UserId == _userManager.GetUserId(User))
            .Include(x => x.Model)
            .Include(x => x.User).ToList();
            return View(configs);
        }

        /// <summary>
        /// Return result page according to simulation id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Result(int id)
        {
            SimulationResultModel m = await _context.SimResltTable.FindAsync(id);
            if (m == null)
            {                
                SimulationConfigurationModel config = await _context.SimConfTable.FindAsync(id);
                List<decimal> sim_settings = new List<decimal>();
                List<decimal> initconds = new List<decimal>();
                string parameters = "[2.1292,4.2584,4.2584,0.1185]";
                sim_settings.Add(config.Solver_StartTime);
                sim_settings.Add(config.Solver_EndTime);
                sim_settings.Add(config.Solver_Interval);
                sim_settings.Add(config.Solver_MaxStep);
                sim_settings.Add(config.Solver_Tighten);
                sim_settings.Add(config.Solver_RelativeTolerance);
                sim_settings.Add(config.Solver_AbsoluteTolerance);
                sim_settings.Add(config.Solver_Timeout);
                Dictionary<string, decimal> IC = JsonConvert.DeserializeObject<Dictionary<string, decimal>>(config.InitialConditions);
                foreach (KeyValuePair<string, decimal> entry in IC)
                {
                    initconds.Add(entry.Value);
                }

                string postData = "{\"sim_settings\":" + JsonConvert.SerializeObject(sim_settings) + ", \"parameters\": " + parameters + ", " +
                    "\"initconds\":" + JsonConvert.SerializeObject(initconds) + "}";

                using (HttpClient client = new HttpClient())
                {
                    using (HttpResponseMessage response = await client.PostAsync("http://model2.simulab.io/", new StringContent("{}", Encoding.UTF8, "application/json")))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            m = new SimulationResultModel();
                            m.Title = (await _context.ModelTable.FindAsync(config.ModelId)).Name;
                            m.Description = config.Date.ToString();
                            string content = await response.Content.ReadAsStringAsync();
                            try
                            {
                                List<List<string>> lines = JsonConvert.DeserializeObject<List<List<string>>>(content);
                                List<List<string>> temp_data = new List<List<string>>();
                                int length = 0;
                                foreach (List<string> line in lines)
                                {
                                    length = line.Count;
                                    if (m.Data == null)
                                    {
                                        for (int i = 0; i < length; i++)
                                        {
                                            temp_data.Add(new List<string>());
                                            temp_data[i].Add(line[i]);
                                        }
                                    }
                                    else
                                    {
                                        for (int i = 1; i < length; i++)
                                        {
                                            temp_data[i].Add(line[i]);
                                        }
                                    }
                                }
                                m.Data = new SimulationDataModel
                                {
                                    Data_x = temp_data[0].ToList(),
                                    Data_y = new List<List<string>>()
                                };
                                for (int i = 1; i < length; i++)
                                {
                                    m.Data.Data_y.Add(temp_data[i].ToList());
                                }
                                m.Result = JsonConvert.SerializeObject(m.Data);
                                _context.SimResltTable.Add(m);
                                await _context.SaveChangesAsync();
                            }
                            catch
                            {
                            }

                        }
                    }
                }
            }
            else
            {
                m.Data = JsonConvert.DeserializeObject<SimulationDataModel>(m.Result);
            }
            return View(m);

            /*
            SimulationResultModel m = new SimulationResultModel();
            m.Title = "Test";
            m.Description = "Description";
            string contentRootPath = _hostingEnvironment.ContentRootPath;
            string[] lines = System.IO.File.ReadAllLines(contentRootPath + @"/Contents/example_01_csv_no_roots.csv");
            int length = 0;
            List<List<string>> temp_data = new List<List<string>>();
            foreach (string line in lines)
            {
                string[] data = line.Split(',');
                length = data.Length;
                if (m.Data == null)
                {
                    for (int i = 0; i < length; i++)
                    {
                        temp_data.Add(new List<string>());
                        temp_data[i].Add(data[i]);
                    }
                }
                else
                {
                    for (int i = 1; i < length; i++)
                    {
                        temp_data[i].Add(data[i]);
                    }
                }
            }
            m.Data = new SimulationDataModel();
            m.Data.Data_x = temp_data[0].ToList();
            m.Data.Data_y = new List<List<string>>();
            for (int i = 1; i < length; i++)
            {
                m.Data.Data_y.Add(temp_data[i].ToList());
            }

            return View(m);*/
        }
    }
}

Simulab/Views/Simulation/Configurator.cshtml
@model Simulab.Models.Database_Models.SimulationConfigurationModel
@using Newtonsoft.Json;
@using Simulab.Models.Database_Models;

@{
    ViewData["Title"] = "Configurator";
 Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container" style="height:100%;">
    <div class="row">
        <div class="col-lg-12" style="padding: 10px 0 10px 0;">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title">Simulation Configurator</h1>
                    @using (Html.BeginForm("Configurator", "Simulation", FormMethod.Post))
                    {
                        @Html.HiddenFor(m => m.UserId);
                        <div class="card border-primary mb-3">
                            <div class="card-body">
                                <div class="form-group">
                                    <div class="dropdown">
                                        @Html.LabelFor(m => m.ModelId, new { @class = "control-label" })
                                        <select class="form-control" data-val="true" data-val-required="The Model ID field is required." id="ModelId"
                                                name="ModelId" onchange="onModelSelect(this.value)" @(Model != null ? "value=" + Model.Model : "")></select>
                                        @Html.ValidationMessageFor(m => m.ModelId, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="DetailSettings" style="display: none">

                            @Html.Partial("ConfiguratorParameterFamilies", Model)

                            @Html.Partial("ConfiguratorEnvironment", Model)

                            @Html.Partial("ConfiguratorSolver", Model)

                            @Html.Partial("ConfiguratorData", Model)

                            <div class="card border-primary mb-3">
                                <div class="card-body" id="ICdiv">
                                </div>
                            </div>

                            <div class="card border-primary mb-3">
                                <div class="card-body">
                                    <div class="form-check">
                                        @Html.CheckBoxFor(m => m.ViewLiveData, new { @class = "form-check-input" })
                                        @Html.LabelFor(m => m.ViewLiveData, new { @class = "form-check-label" })
                                        @Html.ValidationMessageFor(m => m.ViewLiveData, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-check">
                                        @Html.CheckBoxFor(m => m.Notification, new { @class = "form-check-input" })
                                        @Html.LabelFor(m => m.Notification, new { @class = "form-check-label" })
                                        @Html.ValidationMessageFor(m => m.Notification, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <input type="submit" id="sendSimulation" class="btn btn-raised btn-info" value="Start Simulation" />
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    
    var config = @Html.Raw(JsonConvert.SerializeObject(Model));    
    var url = "@Url.Action("ConfiguratorModelSelect", "Simulation")";
    $("#ModelId").load(url, function () {
        if (config.ModelId != 0) {
            $("#DetailSettings").show();
            $("#ModelId").val(config.ModelId);
            onModelSelect(config.ModelId);
        }});
   

    function onModelSelect(id) {
        var url = "@Url.Action("ConfiguratorICs", "Simulation")?id=" + id;
        $("#ICdiv").load(url);
        $("#DetailSettings").show();
    }
</script>

Simulab/Views/Simulation/ConfiguratorData.cshtml
@model Simulab.Models.Database_Models.SimulationConfigurationModel

@using Simulab.Models.Simulations.Enums;

<div class="card border-primary mb-3">
    <div class="card-body">
        <h1 class="card-title">Data Settings</h1>
        <div class="form-group">
            @Html.LabelFor(m => m.Retention, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.Retention, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Retention, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Lifetime, new { @class = "control-label" })
            @Html.DropDownListFor(m => m.Lifetime, Html.GetEnumSelectList(typeof(SimnConfigDataLifeType)), new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Lifetime, "", new { @class = "text-danger" })
        </div>
    </div>
</div>

Simulab/Views/Simulation/ConfiguratorEnvironment.cshtml
@model Simulab.Models.Database_Models.SimulationConfigurationModel

@using Simulab.Models.Simulations.Enums;

<div class="card border-primary mb-3">
    <div class="card-body">
        <h1 class="card-title">Environment Settings</h1>
        <div class="form-group">
            <div class="dropdown">
                @Html.LabelFor(m => m.TreatmentSetting, new { @class = "control-label" })
                @Html.DropDownListFor(m => m.TreatmentSetting, Html.GetEnumSelectList(typeof(SimConfigTreatmentSettingType)), new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.TreatmentSetting, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.TargetEnvironment, new { @class = "control-label" })
            @Html.DropDownListFor(m => m.TargetEnvironment, Html.GetEnumSelectList(typeof(SimConfigTargetEnvironmentType)), new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.TargetEnvironment, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.TargetLanguage, new { @class = "control-label" })
            @Html.DropDownListFor(m => m.TargetLanguage, Html.GetEnumSelectList(typeof(SimConfigTargetLanguageType)), new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.TargetLanguage, "", new { @class = "text-danger" })
        </div>
    </div>
</div>

Simulab/Views/Simulation/ConfiguratorICs.cshtml
@model Simulab.Models.Database_Models.ModelItemModel

@using Newtonsoft.Json;

@{
    List<string> ICList = JsonConvert.DeserializeObject<List<string>>(Model.InitialConditions);
    Dictionary<string, decimal> IC = new Dictionary<string, decimal>();
    foreach (string s in ICList)
    {
        IC.Add(s, 0);
    }
}

<h1 class="card-title">Initial Conditions</h1>
<input type="hidden" id="InitialConditions" name="InitialConditions" value="">
<table class="table">
    <thead>
        <tr>
            <th scope="col">Initial Condition</th>
            <th scope="col">Value</th>
        </tr>
    </thead>
    <tbody>
        @foreach (KeyValuePair<string, decimal> s in IC)
        {
            <tr>
                <td>@s.Key</td>
                <td><input id=@Html.Raw(s.Key) type="number" value=@Html.Raw(s.Value) onchange="onIcChange(this, value)" /></td>
            </tr>
        }
    </tbody>
</table>
@Html.ValidationMessageFor(m => m.InitialConditions, "", new { @class = "text-danger" })

<script>
    var IC = @Html.Raw(JsonConvert.SerializeObject(IC));
    function onIcChange(a, value) {
        IC[a.id] = parseFloat(value);
        var newVal = JSON.stringify(IC);
        $("#InitialConditions").val(newVal);
    }
</script>

Simulab/Views/Simulation/ConfiguratorModelSelect.cshtml
@model List<Simulab.Models.Database_Models.ModelItemModel>
@using Simulab.Models.Database_Models

@if (Model != null)
{
    <option value="" selected disabled hidden>Select Model</option>
    @foreach (ModelItemModel m in Model)
    {
        <option value=@Html.Raw(m.Id)>@Html.Raw(m.Name)</option>
    }
}

Simulab/Views/Simulation/ConfiguratorParameterFamilies.cshtml
@model Simulab.Models.Database_Models.SimulationConfigurationModel

<div class="card border-primary mb-3">
    <div class="card-body">
        <h1 class="card-title">Parameter Families</h1>
        <div class="form-group">
            @Html.LabelFor(m => m.PF_StartTime, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.PF_StartTime, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.PF_StartTime, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.PF_EndTime, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.PF_EndTime, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.PF_EndTime, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.PF_Step, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.PF_Step, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.PF_Step, "", new { @class = "text-danger" })
        </div>
    </div>
</div>

Simulab/Views/Simulation/ConfiguratorSolver.cshtml
@model app.Models.Database_Models.SimulationConfigurationModel

<div class="card border-primary mb-3">
    <div class="card-body">
        <h1 class="card-title">Solver Settings</h1>
        <div class="form-group">
            @Html.LabelFor(m => m.Solver_StartTime, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.Solver_StartTime, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Solver_StartTime, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Solver_EndTime, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.Solver_EndTime, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Solver_EndTime, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Solver_Interval, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.Solver_Interval, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Solver_Interval, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Solver_MaxStep, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.Solver_MaxStep, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Solver_MaxStep, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Solver_Tighten, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.Solver_Tighten, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Solver_Tighten, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Solver_Timeout, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.Solver_Timeout, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Solver_Timeout, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Solver_AbsoluteTolerance, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.Solver_AbsoluteTolerance, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Solver_AbsoluteTolerance, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Solver_RelativeTolerance, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.Solver_RelativeTolerance, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Solver_RelativeTolerance, "", new { @class = "text-danger" })
        </div>
    </div>
</div>

Simulab/Views/Simulation/History.cshtml
@model List<Simulab.Models.Database_Models.SimulationConfigurationModel>

@using Simulab.Models.Database_Models

@{
    ViewData["Title"] = "SimulationHistory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />

@foreach(SimulationConfigurationModel m in Model)
{
    <a href=@Html.Raw(Url.Action("Result", "Simulation") + "?id=" + m.Id.ToString())>
    <div class="card border-primary mb-3" onclick="">
        <div class="card-body">
            <h5 class="card-title">@Html.Raw("Model Name: " + @m.Model.Name)</h5>
            <p class="card-text">@Html.Raw("Execution Time: " + m.Date + "\tCreated By: " + @m.User.UserName)</p>
        </div>
    </div>
    </a>

}

Simulab/Views/Simulation/Result.cshtml
@model Simulab.Models.Database_Models.SimulationResultModel

@using Newtonsoft.Json;

@{
    ViewData["Title"] = "Result";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/node_modules/lodash/lodash.js"></script>
<script src="~/node_modules/gridstack/dist/gridstack.all.js"></script>
<link href="~/node_modules/gridstack/dist/gridstack.css" rel="stylesheet" />
<script src="~/node_modules/plotly.js/dist/plotly.js"></script>

<div class="container-fluid" style="padding: 10px 7px 10px 7px;">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">

                    <h2>@Model.Title</h2>
                    <h5>@Model.Description</h5>

                    <div class="grid-stack" data-gs-width="12" data-gs-animate="yes" data-gs-current-height="6">
                        @{
                            int col = 0;
                            int row = 0;
                        }
                        @for (int i = 0; i < Model.Data.Data_y.Count; i++)
                        {
                            <div class="grid-stack-item ui-draggable ui-resizable card border-primary mb-5" data-gs-x=@Html.Raw(col * 4) data-gs-y=@Html.Raw(row * 4) data-gs-auto-position data-gs-width="4" data-gs-height="4">
                                <div class="grid-stack-item-content ui-draggable-handle">
                                    <div id=@Html.Raw("plotly" + i) class=""></div>
                                </div>
                            </div>
                            col++;
                            if (col == 3)
                            {
                                row++;
                                col = 0;
                            }
                        }
                    </div>

                    <script type="text/javascript" id="code">
                        var d3 = Plotly.d3;
                        $('.grid-stack').gridstack({
                            width: 12,
                            disableResize: false,
                            autosize:true,
                            handle:'grid-stack-item-content',
                            handleClass: 'grid-stack-item-content',
                            alwaysShowResizeHandle: true,
                            resizable: {
                                handles: 'se'
                            }
                        });

                        function SetPlotly(id, data_x, data_y) {
                            var innerPlotData = {
                                x: [],
                                y: [],
                                type: 'scatter'
                            };

                            innerPlotData.x = data_x;
                            innerPlotData.y = data_y;

                            var layout = {title: (id + 1)}

                            var plotData = [innerPlotData];
                                /*
                                var d3 = Plotly.d3;
                                var WIDTH_IN_PERCENT_OF_PARENT = 100,
                                    HEIGHT_IN_PERCENT_OF_PARENT = 50;

                                var gd3 = d3.selectAll(".responsive-plot")
                                    .style({
                                        width: WIDTH_IN_PERCENT_OF_PARENT + '%',
                                        'margin-left': (100 - WIDTH_IN_PERCENT_OF_PARENT) / 2 + '%',

                                        height: HEIGHT_IN_PERCENT_OF_PARENT + '%',
                                        'margin-top': (100 - HEIGHT_IN_PERCENT_OF_PARENT) / 2 + 'vh'
                                    });

                                var nodes_to_resize = gd3[0]; //not sure why but the goods are within a nested array
                                window.onresize = function () {
                                    for (var i = 0; i < nodes_to_resize.length; i++) {
                                        Plotly.Plots.resize(nodes_to_resize[i]);
                                    }
                                }*/
                            Plotly.newPlot("plotly" + id, plotData, layout);
                         }

                        var result = @Html.Raw(JsonConvert.SerializeObject(Model));

                        var length = result.Data.Data_y.length;
                        for (var i = 0; i < length; i++) {
                            SetPlotly(i, result.Data.Data_x, result.Data.Data_y[i]);
                            //resize after plot to fit div
                            $("#plotly" + i).one('plotly_afterplot', (data) => {
                                var element = data.currentTarget.parentNode.parentNode;
                                var update = {
                                    width: element.offsetWidth,
                                    height: element.offsetHeight
                                };
                                Plotly.relayout(data.currentTarget, update);
                            });
                        }

                        //Gridstack trigger plotly
                        $('.grid-stack')
                            .on('resizestop', (event, ui) => {
                                var grid = this;
                                var element = event.target;
                                console.log(element);
                                var gd3 = d3.select(element)
                                    .select(".js-plotly-plot");
                                var gd = gd3.node();
                                var update = {
                                    width: element.offsetWidth,
                                    height: element.offsetHeight
                                };
                                Plotly.relayout(gd, update);

                            });

                        //Window resize plotly
                        window.addEventListener("resize", (event, items) => {
                            var gd3 = d3.selectAll(".js-plotly-plot");
                            gd3[0].forEach((item) => { 
                                var element = item.parentNode.parentNode;
                                var update = {
                                    width: element.offsetWidth,
                                    height: element.offsetHeight
                                };
                                Plotly.relayout(item, update);
                            })
                        })
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>

Simulab/Views/Simulation/Simulation.cshtml

@{
    ViewData["Title"] = "Simulation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container" style="height:100%;">
    <div class="row">
        <div class="col-lg-12" style="padding: 10px 0 10px 0;">
            <div class="card border-primary mb-3">
                <div class="card-body">
                    <h1 class="card-title">Simulations</h1>
                    <h6 class="card-subtitle mb-2 text-muted">Create, Edit, View and Delete Models</h6>
                    <div class="form-group">
                        <Button name="newSimulation" class="btn btn-raised btn-info" onclick="location.href='@Url.Action("Configurator", "Simulation")'">New Simulation</Button>
                        <Button name="simulationHistory" class="btn btn-raised btn-info" onclick="location.href='@Url.Action("History", "Simulation")'">Simulation History</Button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
