Simulab/Controllers/RootController.cs
using System.Threading.Tasks;
using Simulab.Models;
using Simulab.Models.Database_Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Simulab.Controllers
{
  public class RootController : Controller
    {
        private readonly UserManager<UserModel> _userManager;
        private readonly SignInManager<UserModel> _signInManager;
        public RootController(UserManager<UserModel> userManager, SignInManager<UserModel> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        /// Get the login page
        /// </summary>
        /// <returns></returns>
        [Route("~/Login")]
        public IActionResult Login()
        {
            return View();
        }

        /// <summary>
        /// Submit login request
        /// </summary>
        /// <param name="m"></param>
        /// <param name="returnUrl">Url to return after login</param>
        /// <returns></returns>
        [HttpPost("~/Login")]
        public async Task<IActionResult> Login(UserLoginModel m, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(m.Username, 
                    m.Password, m.RememberMe, lockoutOnFailure: false);
                /*
                if (result.RequiresTwoFactor)
                {
                    return RedirectToAction(nameof(SendCode), new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                }
                */
                if (result.IsLockedOut)
                {
                    ModelState.AddModelError(string.Empty, "User account locked out.");
                    return View("Lockout");
                }
                else if (result.Succeeded)
                {
                    if (!string.IsNullOrEmpty(returnUrl)) return Redirect(returnUrl);
                }
                else
                {
                    ViewBag.ErrorMessage = "Incorrect Username or Password.";
                    return View(m);
                }
            }
            return RedirectToAction(nameof(ModelController.MView), "Model");
        }
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction(nameof(ModelController.MView), "Model");
        }

        /// <summary>
        /// Return register page
        /// </summary>
        /// <returns></returns>
        [Route("~/Register")]
        public IActionResult Register()
        {
            return View(new UserCreateModel());
        }

        /// <summary>
        /// Submit registration request
        /// </summary>
        /// <param name="m"></param>
        /// <returns></returns>
        [HttpPost("~/Register")]
        public async Task<IActionResult> Register(UserCreateModel m)
        {
            if (ModelState.IsValid)
            {
                var user = new UserModel { UserName = m.Username, Email = m.Email };
                var result = await _userManager.CreateAsync(user, m.Password);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToAction("View", "Model");
                }
            }
            return View(m);
        }
    }
}

Simulab/Controllers/TeamController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Simulab.Models.Database_Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Simulab.Controllers
{
    [Authorize]
    public class TeamController : Controller
    {
        private SimulabContext _context = new SimulabContext();
        private readonly UserManager<UserModel> _userManager;

        public TeamController(UserManager<UserModel> userManager)
        {
            _userManager = userManager;
        }

        /// <summary>
        /// Return team create page
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Submit team create request
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Create(TeamModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    UserModel user = await _context.UserTable.FirstOrDefaultAsync(x => x.UserName == User.Identity.Name);
                    TeamMemberModel teamPerm = new TeamMemberModel
                    {
                        R_Perm = 7,
                        W_Perm = 7,
                        X_Perm = 7,
                        User = user,
                        Team = model
                    };
                    _context.TeamMemberTable.Add(teamPerm);
                    model.Users = new List<TeamMemberModel>();
                    model.Users.Add(teamPerm);
                    await _context.Entry(user).Collection(c => c.Teams).LoadAsync();
                    user.Teams.Add(teamPerm);
                    await _context.SaveChangesAsync();
                }
                catch { ViewBag.Message = "Internal Error"; }
            }
            return RedirectToAction("Team", "User");
        }

        /// <summary>
        /// Return team update page
        /// </summary>
        /// <param name="teamId"></param>
        /// <returns></returns>
        public async Task<IActionResult> Update(int teamId)
        {
            TeamModel team = await _context.TeamTable.Where(x => x.Id == teamId)
                .Include(x => x.Users).FirstOrDefaultAsync();
            foreach (TeamMemberModel t in team.Users)
            {
                await _context.Entry(t).Reference(r => r.User).LoadAsync();
            }
            return PartialView(team);
        }

        /// <summary>
        /// Submit team update request
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> SubmitUpdate(TeamModel model)
        {
            TeamModel t = await _context.TeamTable.FindAsync(model.Id);
            t.Name = model.Name;
            t.Description = model.Description;
            await _context.SaveChangesAsync();
            return RedirectToAction("Team", "User");
        }

        /// <summary>
        /// Return add team user page
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> AddUser()
        {
            return PartialView();
        }

        /// <summary>
        /// Submit add team user request
        /// </summary>
        /// <param name="m"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> AddUser(TeamMemberModel m)
        {
            TeamMemberModel _currentUserPerm = await _context.TeamMemberTable.FirstOrDefaultAsync(_x => _x.User.UserName == User.Identity.Name);
            if (_currentUserPerm.R_Perm < m.R_Perm || _currentUserPerm.W_Perm < m.W_Perm || _currentUserPerm.X_Perm < m.X_Perm)
            {
                UserModel user = await _context.UserTable.Where(x => x.UserName.ToUpper() == m.User.UserName.ToUpper()).Include(x => x.Teams).FirstOrDefaultAsync();
                foreach (TeamMemberModel t in user.Teams)
                {
                    _context.Entry(t).Reference(x => x.Team).Load();
                }
                if (user.Teams.FirstOrDefault(x => x.Team.Id == m.Team.Id) != null)
                {
                    return StatusCode(409);
                }
                TeamModel team = await _context.TeamTable.FirstOrDefaultAsync(x => x.Id == m.Team.Id);
                try
                {
                    m.User = user;
                    m.Team = team;
                    await _context.TeamMemberTable.AddAsync(m);
                    await _context.SaveChangesAsync();
                    return Ok();
                }
                catch { }
                return StatusCode(500);
            }
            return Forbid();
        }

        /// <summary>
        /// Submit update team user request
        /// </summary>
        /// <param name="id"></param>
        /// <param name="r">Read permission</param>
        /// <param name="w">Write permission</param>
        /// <param name="x">Exec permission</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> UpdateUser(int id, int r, int w, int x)
        {
            TeamMemberModel m = await _context.TeamMemberTable.FirstOrDefaultAsync(_x => _x.Id == id);
            TeamMemberModel _currentUserPerm = await _context.TeamMemberTable.FirstOrDefaultAsync(_x => _x.User.UserName == User.Identity.Name);
            if (w < _currentUserPerm.W_Perm)
            {
                m.R_Perm = r;
                m.W_Perm = w;
                m.X_Perm = x;
                await _context.SaveChangesAsync();
                return Ok();
            }
            return Forbid();
        }

        /// <summary>
        /// Submit remove user from team request
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> RemoveUser(int id)
        {
            try
            {
                TeamMemberModel teamPerm = await _context.TeamMemberTable.Where(x => x.Id == id).Include(x => x.User).FirstOrDefaultAsync();
                TeamMemberModel _currentUserPerm = await _context.TeamMemberTable.FirstOrDefaultAsync(_x => _x.User.UserName == User.Identity.Name);
                if (teamPerm.User.UserName != User.Identity.Name && teamPerm.W_Perm < _currentUserPerm.W_Perm)
                {
                    _context.TeamMemberTable.Remove(teamPerm);
                    await _context.SaveChangesAsync();
                    return Ok();
                }
                else
                {
                    return Forbid();
                }
            }
            catch { return new StatusCodeResult(500); }
        }
        
    }
}

Simulab/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Simulab.Models.Database_Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Simulab.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private SimulabContext _context = new SimulabContext();
        private readonly UserManager<UserModel> _userManager;
        public UserController(UserManager<UserModel> userManager)
        {
            _userManager = userManager;
        }

        /// <summary>
        /// Return account page
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Account()
        {
            UserModel user = await _userManager.FindByNameAsync(User.Identity.Name);
            return View(user);
        }

        /// <summary>
        /// Update user account
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Account(UserModel user)
        {
            if (ModelState.IsValid)
            {
                _context.UserTable.Update(user);
                await _context.SaveChangesAsync();
            }
            else
            {
                ViewBag.Message = "Input Invalid";
            }
            return View(user);
        }

        /// <summary>
        /// return user teams page
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Team()
        {
            UserModel user = await _context.UserTable.Where(x => x.UserName == User.Identity.Name)
                .Include(c => c.Teams).FirstOrDefaultAsync();
            foreach (TeamMemberModel m in user.Teams)
            {
                await _context.Entry(m).Reference(p => p.Team).LoadAsync();
            }
            return View(user);
        }

        /// <summary>
        /// Find user by email or username
        /// </summary>
        /// <param name="filter"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> FindUser(string filter)
        {
            UserModel user = await _context.UserTable.FirstOrDefaultAsync(x => x.UserName == filter || x.Email == filter);
            if (user != null)
            {
                return Ok();
            }
            else
            {
                return NotFound();
            }
        }
    }
}

Simulab/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <!-- CSS -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">
    <link rel="stylesheet" href="~/node_modules/bootstrap-material-design/dist/css/bootstrap-material-design.css">
    <link rel="stylesheet" href="~/Contents/Site.css">
    <!-- JS Libs -->
    <script src="~/node_modules/jquery/dist/jquery.js"></script>
    <script src="~/node_modules/jquery-ui-dist/jquery-ui.js"></script>
    <script src="~/node_modules/popper.js/dist/umd/popper.js"></script>
    <script src="~/node_modules/bootstrap-material-design/dist/js/bootstrap-material-design.js"></script>
    <script src="~/node_modules/ace-builds/src/ace.js"></script>
    <script src="~/node_modules/ace-builds/src/theme-monokai.js"></script>
    <meta name="viewport" content="width=device-width" />
    <title>Simulab.io</title>
</head>
<body style="background-color:#232322;">
    <div id="root" style="height: 100%;">
        @Html.Partial("_Navbar")
        <div id="app">
            @RenderBody()
        </div>
    </div>
</body>
</html>

Simulab/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Simulab.io</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "model" ? "active" : "")">
            @Html.ActionLink("Model", "MView", "Model")</li>
        <li class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "simulation" ? "active" : "")">
            @Html.ActionLink("Simulation", "Simulation", "Simulation")</li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    @Html.Partial("_User")
  </div>
</nav>

Simulab/Views/Shared/_Team.cshtml
@model Simulab.Models.Database_Models.TeamModel

<div>
    <h4>TeamModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Simulab/Views/Shared/_User.cshtml
@{
    string Username = User.Identity.Name;
}

@if (!String.IsNullOrEmpty(Username))
{
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            @Username
        </button>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="dropdownMenuButton"  style="right:1px; left:auto;">
            @Html.ActionLink("Settings", "Account", "User", null, new { @class = "dropdown-item" })
            @Html.ActionLink("Logout", "Logout", "Root", null, new { @class = "dropdown-item" })
        </div>
    </div>
}